"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const dashboard_routes_1 = __importDefault(require("./dashboard.routes"));
const users_routes_1 = __importDefault(require("./users.routes"));
const partners_routes_1 = __importDefault(require("./partners.routes"));
const pharmacies_routes_1 = __importDefault(require("./pharmacies.routes"));
const quotes_routes_1 = __importDefault(require("./quotes.routes"));
const workflow_routes_1 = __importDefault(require("./workflow.routes"));
const analytics_routes_1 = __importDefault(require("./analytics.routes"));
const config_routes_1 = __importDefault(require("./config.routes"));
const reports_routes_1 = __importDefault(require("./reports.routes"));
const approvals_routes_1 = __importDefault(require("./approvals.routes"));
const challenges_routes_1 = __importDefault(require("./challenges.routes"));
const financial_routes_1 = __importDefault(require("./financial.routes"));
const profile_routes_1 = __importDefault(require("./profile.routes"));
const gamification_routes_1 = __importDefault(require("./gamification.routes"));
const support_routes_1 = __importDefault(require("./support.routes"));
const security_routes_1 = __importDefault(require("./security.routes"));
const audit_routes_1 = __importDefault(require("./audit.routes"));
const integrations_routes_1 = __importDefault(require("./integrations.routes"));
const content_routes_1 = __importDefault(require("./content.routes"));
const dev_routes_1 = __importDefault(require("./dev.routes"));
const router = (0, express_1.Router)();
router.use(content_routes_1.default);
router.use(dashboard_routes_1.default);
router.use(users_routes_1.default);
router.use(partners_routes_1.default);
router.use(pharmacies_routes_1.default);
router.use(quotes_routes_1.default);
router.use(workflow_routes_1.default);
router.use(analytics_routes_1.default);
router.use(config_routes_1.default);
router.use(reports_routes_1.default);
router.use(approvals_routes_1.default);
router.use(challenges_routes_1.default);
router.use(financial_routes_1.default);
router.use(profile_routes_1.default);
router.use(gamification_routes_1.default);
router.use(support_routes_1.default);
router.use(security_routes_1.default);
router.use(audit_routes_1.default);
router.use(integrations_routes_1.default);
router.use('/dev', dev_routes_1.default);
exports.default = router;
//# sourceMappingURL=index.js.map