# redeploy: 2026-03-20
[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "sh ./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/api/health"
httpMethod = "GET"
timeoutSeconds = 30
