import { Prisma } from '../../lib/generated/prisma/index.js';
export declare const PartnerCrud: {
    create(data: any): Promise<{
        type: string;
        name: string | null;
        id: string;
        personId: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        description: string | null;
        specialty: string | null;
        userId: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        settings: Prisma.JsonValue | null;
        photo: string | null;
        crm: string | null;
        specialties: string[];
        institution: string | null;
        experience: number | null;
        experienceYears: number | null;
        rating: number | null;
        totalReviews: number;
        verified: boolean;
        isApproved: boolean;
        rejectionReason: string | null;
        lat: number | null;
        lng: number | null;
        acceptsEmergency: boolean;
        acceptsInsurance: boolean;
        acceptsOnline: boolean;
        acceptsTelemedicine: boolean;
        cnpj: string | null;
        consultationPrice: number | null;
        education: Prisma.JsonValue | null;
        facilities: string[];
        foundationYear: number | null;
        insurances: string[];
        languages: string[];
        workingHours: Prisma.JsonValue | null;
    }>;
    findById(id: string): Promise<{
        type: string;
        name: string | null;
        id: string;
        personId: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        description: string | null;
        specialty: string | null;
        userId: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        settings: Prisma.JsonValue | null;
        photo: string | null;
        crm: string | null;
        specialties: string[];
        institution: string | null;
        experience: number | null;
        experienceYears: number | null;
        rating: number | null;
        totalReviews: number;
        verified: boolean;
        isApproved: boolean;
        rejectionReason: string | null;
        lat: number | null;
        lng: number | null;
        acceptsEmergency: boolean;
        acceptsInsurance: boolean;
        acceptsOnline: boolean;
        acceptsTelemedicine: boolean;
        cnpj: string | null;
        consultationPrice: number | null;
        education: Prisma.JsonValue | null;
        facilities: string[];
        foundationYear: number | null;
        insurances: string[];
        languages: string[];
        workingHours: Prisma.JsonValue | null;
    }>;
    findByUserId(userId: string): Promise<{
        type: string;
        name: string | null;
        id: string;
        personId: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        description: string | null;
        specialty: string | null;
        userId: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        settings: Prisma.JsonValue | null;
        photo: string | null;
        crm: string | null;
        specialties: string[];
        institution: string | null;
        experience: number | null;
        experienceYears: number | null;
        rating: number | null;
        totalReviews: number;
        verified: boolean;
        isApproved: boolean;
        rejectionReason: string | null;
        lat: number | null;
        lng: number | null;
        acceptsEmergency: boolean;
        acceptsInsurance: boolean;
        acceptsOnline: boolean;
        acceptsTelemedicine: boolean;
        cnpj: string | null;
        consultationPrice: number | null;
        education: Prisma.JsonValue | null;
        facilities: string[];
        foundationYear: number | null;
        insurances: string[];
        languages: string[];
        workingHours: Prisma.JsonValue | null;
    }>;
    update(id: string, data: any): Promise<{
        type: string;
        name: string | null;
        id: string;
        personId: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        description: string | null;
        specialty: string | null;
        userId: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        settings: Prisma.JsonValue | null;
        photo: string | null;
        crm: string | null;
        specialties: string[];
        institution: string | null;
        experience: number | null;
        experienceYears: number | null;
        rating: number | null;
        totalReviews: number;
        verified: boolean;
        isApproved: boolean;
        rejectionReason: string | null;
        lat: number | null;
        lng: number | null;
        acceptsEmergency: boolean;
        acceptsInsurance: boolean;
        acceptsOnline: boolean;
        acceptsTelemedicine: boolean;
        cnpj: string | null;
        consultationPrice: number | null;
        education: Prisma.JsonValue | null;
        facilities: string[];
        foundationYear: number | null;
        insurances: string[];
        languages: string[];
        workingHours: Prisma.JsonValue | null;
    }>;
    delete(id: string): Promise<{
        type: string;
        name: string | null;
        id: string;
        personId: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        description: string | null;
        specialty: string | null;
        userId: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        settings: Prisma.JsonValue | null;
        photo: string | null;
        crm: string | null;
        specialties: string[];
        institution: string | null;
        experience: number | null;
        experienceYears: number | null;
        rating: number | null;
        totalReviews: number;
        verified: boolean;
        isApproved: boolean;
        rejectionReason: string | null;
        lat: number | null;
        lng: number | null;
        acceptsEmergency: boolean;
        acceptsInsurance: boolean;
        acceptsOnline: boolean;
        acceptsTelemedicine: boolean;
        cnpj: string | null;
        consultationPrice: number | null;
        education: Prisma.JsonValue | null;
        facilities: string[];
        foundationYear: number | null;
        insurances: string[];
        languages: string[];
        workingHours: Prisma.JsonValue | null;
    }>;
    list(): Promise<{
        type: string;
        name: string | null;
        id: string;
        personId: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        description: string | null;
        specialty: string | null;
        userId: string | null;
        address: string | null;
        city: string | null;
        state: string | null;
        zipCode: string | null;
        settings: Prisma.JsonValue | null;
        photo: string | null;
        crm: string | null;
        specialties: string[];
        institution: string | null;
        experience: number | null;
        experienceYears: number | null;
        rating: number | null;
        totalReviews: number;
        verified: boolean;
        isApproved: boolean;
        rejectionReason: string | null;
        lat: number | null;
        lng: number | null;
        acceptsEmergency: boolean;
        acceptsInsurance: boolean;
        acceptsOnline: boolean;
        acceptsTelemedicine: boolean;
        cnpj: string | null;
        consultationPrice: number | null;
        education: Prisma.JsonValue | null;
        facilities: string[];
        foundationYear: number | null;
        insurances: string[];
        languages: string[];
        workingHours: Prisma.JsonValue | null;
    }[]>;
};
//# sourceMappingURL=partner.crud.d.ts.map