export declare const PatientCrud: {
    create(data: any): Promise<{
        level: number;
        id: string;
        personId: string | null;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        medications: string | null;
        allergies: string[];
        userId: string | null;
        levelTitle: string | null;
        cpf: string | null;
        blockchainAddress: string | null;
        referralCode: string | null;
        address: string | null;
        birthDate: Date | null;
        bloodType: string | null;
        chronicDiseases: string[];
        city: string | null;
        currentMedications: string[];
        currentStreak: number;
        emergencyContact: string | null;
        emergencyPhone: string | null;
        gender: string | null;
        healthPoints: number;
        lastActiveDate: Date | null;
        longestStreak: number;
        state: string | null;
        zipCode: string | null;
        archetype: string | null;
        dateOfBirth: Date | null;
        encryptionPublicKey: string | null;
        experiencePoints: number;
        healthGoals: string[];
        levelTier: string | null;
        lifestyle: import("lib/generated/prisma/runtime/library").JsonValue | null;
        onboardingCompleted: boolean;
        referralCount: number;
        referralEarnings: number;
        referredBy: string | null;
        settings: import("lib/generated/prisma/runtime/library").JsonValue | null;
        totalBadgesEarned: number;
        totalChallengesCompleted: number;
        userIntent: string | null;
        userPriority: string | null;
        familyGroupId: string | null;
        familyRole: string | null;
    }>;
    findById(id: string): Promise<{
        level: number;
        id: string;
        personId: string | null;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        medications: string | null;
        allergies: string[];
        userId: string | null;
        levelTitle: string | null;
        cpf: string | null;
        blockchainAddress: string | null;
        referralCode: string | null;
        address: string | null;
        birthDate: Date | null;
        bloodType: string | null;
        chronicDiseases: string[];
        city: string | null;
        currentMedications: string[];
        currentStreak: number;
        emergencyContact: string | null;
        emergencyPhone: string | null;
        gender: string | null;
        healthPoints: number;
        lastActiveDate: Date | null;
        longestStreak: number;
        state: string | null;
        zipCode: string | null;
        archetype: string | null;
        dateOfBirth: Date | null;
        encryptionPublicKey: string | null;
        experiencePoints: number;
        healthGoals: string[];
        levelTier: string | null;
        lifestyle: import("lib/generated/prisma/runtime/library").JsonValue | null;
        onboardingCompleted: boolean;
        referralCount: number;
        referralEarnings: number;
        referredBy: string | null;
        settings: import("lib/generated/prisma/runtime/library").JsonValue | null;
        totalBadgesEarned: number;
        totalChallengesCompleted: number;
        userIntent: string | null;
        userPriority: string | null;
        familyGroupId: string | null;
        familyRole: string | null;
    }>;
    findByUserId(userId: string): Promise<{
        level: number;
        id: string;
        personId: string | null;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        medications: string | null;
        allergies: string[];
        userId: string | null;
        levelTitle: string | null;
        cpf: string | null;
        blockchainAddress: string | null;
        referralCode: string | null;
        address: string | null;
        birthDate: Date | null;
        bloodType: string | null;
        chronicDiseases: string[];
        city: string | null;
        currentMedications: string[];
        currentStreak: number;
        emergencyContact: string | null;
        emergencyPhone: string | null;
        gender: string | null;
        healthPoints: number;
        lastActiveDate: Date | null;
        longestStreak: number;
        state: string | null;
        zipCode: string | null;
        archetype: string | null;
        dateOfBirth: Date | null;
        encryptionPublicKey: string | null;
        experiencePoints: number;
        healthGoals: string[];
        levelTier: string | null;
        lifestyle: import("lib/generated/prisma/runtime/library").JsonValue | null;
        onboardingCompleted: boolean;
        referralCount: number;
        referralEarnings: number;
        referredBy: string | null;
        settings: import("lib/generated/prisma/runtime/library").JsonValue | null;
        totalBadgesEarned: number;
        totalChallengesCompleted: number;
        userIntent: string | null;
        userPriority: string | null;
        familyGroupId: string | null;
        familyRole: string | null;
    }>;
    update(id: string, data: any): Promise<{
        level: number;
        id: string;
        personId: string | null;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        medications: string | null;
        allergies: string[];
        userId: string | null;
        levelTitle: string | null;
        cpf: string | null;
        blockchainAddress: string | null;
        referralCode: string | null;
        address: string | null;
        birthDate: Date | null;
        bloodType: string | null;
        chronicDiseases: string[];
        city: string | null;
        currentMedications: string[];
        currentStreak: number;
        emergencyContact: string | null;
        emergencyPhone: string | null;
        gender: string | null;
        healthPoints: number;
        lastActiveDate: Date | null;
        longestStreak: number;
        state: string | null;
        zipCode: string | null;
        archetype: string | null;
        dateOfBirth: Date | null;
        encryptionPublicKey: string | null;
        experiencePoints: number;
        healthGoals: string[];
        levelTier: string | null;
        lifestyle: import("lib/generated/prisma/runtime/library").JsonValue | null;
        onboardingCompleted: boolean;
        referralCount: number;
        referralEarnings: number;
        referredBy: string | null;
        settings: import("lib/generated/prisma/runtime/library").JsonValue | null;
        totalBadgesEarned: number;
        totalChallengesCompleted: number;
        userIntent: string | null;
        userPriority: string | null;
        familyGroupId: string | null;
        familyRole: string | null;
    }>;
    delete(id: string): Promise<{
        level: number;
        id: string;
        personId: string | null;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        medications: string | null;
        allergies: string[];
        userId: string | null;
        levelTitle: string | null;
        cpf: string | null;
        blockchainAddress: string | null;
        referralCode: string | null;
        address: string | null;
        birthDate: Date | null;
        bloodType: string | null;
        chronicDiseases: string[];
        city: string | null;
        currentMedications: string[];
        currentStreak: number;
        emergencyContact: string | null;
        emergencyPhone: string | null;
        gender: string | null;
        healthPoints: number;
        lastActiveDate: Date | null;
        longestStreak: number;
        state: string | null;
        zipCode: string | null;
        archetype: string | null;
        dateOfBirth: Date | null;
        encryptionPublicKey: string | null;
        experiencePoints: number;
        healthGoals: string[];
        levelTier: string | null;
        lifestyle: import("lib/generated/prisma/runtime/library").JsonValue | null;
        onboardingCompleted: boolean;
        referralCount: number;
        referralEarnings: number;
        referredBy: string | null;
        settings: import("lib/generated/prisma/runtime/library").JsonValue | null;
        totalBadgesEarned: number;
        totalChallengesCompleted: number;
        userIntent: string | null;
        userPriority: string | null;
        familyGroupId: string | null;
        familyRole: string | null;
    }>;
    list(): Promise<{
        level: number;
        id: string;
        personId: string | null;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string | null;
        medications: string | null;
        allergies: string[];
        userId: string | null;
        levelTitle: string | null;
        cpf: string | null;
        blockchainAddress: string | null;
        referralCode: string | null;
        address: string | null;
        birthDate: Date | null;
        bloodType: string | null;
        chronicDiseases: string[];
        city: string | null;
        currentMedications: string[];
        currentStreak: number;
        emergencyContact: string | null;
        emergencyPhone: string | null;
        gender: string | null;
        healthPoints: number;
        lastActiveDate: Date | null;
        longestStreak: number;
        state: string | null;
        zipCode: string | null;
        archetype: string | null;
        dateOfBirth: Date | null;
        encryptionPublicKey: string | null;
        experiencePoints: number;
        healthGoals: string[];
        levelTier: string | null;
        lifestyle: import("lib/generated/prisma/runtime/library").JsonValue | null;
        onboardingCompleted: boolean;
        referralCount: number;
        referralEarnings: number;
        referredBy: string | null;
        settings: import("lib/generated/prisma/runtime/library").JsonValue | null;
        totalBadgesEarned: number;
        totalChallengesCompleted: number;
        userIntent: string | null;
        userPriority: string | null;
        familyGroupId: string | null;
        familyRole: string | null;
    }[]>;
};
//# sourceMappingURL=patient.crud.d.ts.map