export enum AnalyticsType {
    SALES = "SALES",
    INVENTORY = "INVENTORY",
    PERFORMANCE = "PERFORMANCE",
    DEMAND = "DEMAND",
    PRICING = "PRICING",
    CUSTOMER = "CUSTOMER",
    OPERATIONAL = "OPERATIONAL",
}

export enum ForecastModel {
    ARIMA = "ARIMA",
    PROPHET = "PROPHET",
    LINEAR_REGRESSION = "LINEAR_REGRESSION",
    RANDOM_FOREST = "RANDOM_FOREST",
    LSTM = "LSTM",
    ENSEMBLE = "ENSEMBLE",
}

export enum InsightType {
    TREND = "TREND",
    ANOMALY = "ANOMALY",
    OPPORTUNITY = "OPPORTUNITY",
    WARNING = "WARNING",
    RECOMMENDATION = "RECOMMENDATION",
    PREDICTION = "PREDICTION",
}

export enum ReportType {
    DAILY = "DAILY",
    WEEKLY = "WEEKLY",
    MONTHLY = "MONTHLY",
    QUARTERLY = "QUARTERLY",
    YEARLY = "YEARLY",
    CUSTOM = "CUSTOM",
}
