import { z } from 'zod';
/**
 * Schema de validação para variáveis de ambiente
 * Garante que todas as configurações críticas estejam presentes e válidas
 */
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    CORS_ORIGIN: z.ZodOptional<z.ZodString>;
    JWT_SECRET: z.ZodString;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    SUPABASE_URL: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    SUPABASE_ANON_KEY: z.ZodOptional<z.ZodString>;
    SUPABASE_SERVICE_ROLE_KEY: z.ZodOptional<z.ZodString>;
    SMTP_HOST: z.ZodOptional<z.ZodString>;
    SMTP_PORT: z.ZodOptional<z.ZodPipeline<z.ZodEffects<z.ZodString, number, string>, z.ZodNumber>>;
    SMTP_USER: z.ZodOptional<z.ZodString>;
    SMTP_PASS: z.ZodOptional<z.ZodString>;
    FROM_EMAIL: z.ZodOptional<z.ZodString>;
    FROM_NAME: z.ZodOptional<z.ZodString>;
    VAPID_PUBLIC_KEY: z.ZodOptional<z.ZodString>;
    VAPID_PRIVATE_KEY: z.ZodOptional<z.ZodString>;
    VAPID_SUBJECT: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    ENABLE_CRON_JOBS: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["error", "warn", "info", "debug"]>>;
    RATE_LIMIT_WINDOW_MS: z.ZodDefault<z.ZodPipeline<z.ZodEffects<z.ZodString, number, string>, z.ZodNumber>>;
    RATE_LIMIT_MAX_REQUESTS: z.ZodDefault<z.ZodPipeline<z.ZodEffects<z.ZodString, number, string>, z.ZodNumber>>;
    AUTH_RATE_LIMIT_MAX_REQUESTS: z.ZodDefault<z.ZodPipeline<z.ZodEffects<z.ZodString, number, string>, z.ZodNumber>>;
    BCRYPT_ROUNDS: z.ZodDefault<z.ZodPipeline<z.ZodEffects<z.ZodString, number, string>, z.ZodNumber>>;
    ADMIN_DEV_BYPASS: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
    ADMIN_DEV_USER_ID: z.ZodDefault<z.ZodString>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV?: "development" | "production" | "test";
    PORT?: number;
    CORS_ORIGIN?: string;
    JWT_SECRET?: string;
    JWT_EXPIRES_IN?: string;
    DATABASE_URL?: string;
    REDIS_URL?: string;
    SUPABASE_URL?: string;
    SUPABASE_ANON_KEY?: string;
    SUPABASE_SERVICE_ROLE_KEY?: string;
    SMTP_HOST?: string;
    SMTP_PORT?: number;
    SMTP_USER?: string;
    SMTP_PASS?: string;
    FROM_EMAIL?: string;
    FROM_NAME?: string;
    VAPID_PUBLIC_KEY?: string;
    VAPID_PRIVATE_KEY?: string;
    VAPID_SUBJECT?: string;
    ENABLE_CRON_JOBS?: boolean;
    LOG_LEVEL?: "error" | "warn" | "info" | "debug";
    RATE_LIMIT_WINDOW_MS?: number;
    RATE_LIMIT_MAX_REQUESTS?: number;
    AUTH_RATE_LIMIT_MAX_REQUESTS?: number;
    BCRYPT_ROUNDS?: number;
    ADMIN_DEV_BYPASS?: boolean;
    ADMIN_DEV_USER_ID?: string;
    OPENAI_API_KEY?: string;
}, {
    NODE_ENV?: "development" | "production" | "test";
    PORT?: number;
    CORS_ORIGIN?: string;
    JWT_SECRET?: string;
    JWT_EXPIRES_IN?: string;
    DATABASE_URL?: string;
    REDIS_URL?: string;
    SUPABASE_URL?: string;
    SUPABASE_ANON_KEY?: string;
    SUPABASE_SERVICE_ROLE_KEY?: string;
    SMTP_HOST?: string;
    SMTP_PORT?: string;
    SMTP_USER?: string;
    SMTP_PASS?: string;
    FROM_EMAIL?: string;
    FROM_NAME?: string;
    VAPID_PUBLIC_KEY?: string;
    VAPID_PRIVATE_KEY?: string;
    VAPID_SUBJECT?: string;
    ENABLE_CRON_JOBS?: string;
    LOG_LEVEL?: "error" | "warn" | "info" | "debug";
    RATE_LIMIT_WINDOW_MS?: string;
    RATE_LIMIT_MAX_REQUESTS?: string;
    AUTH_RATE_LIMIT_MAX_REQUESTS?: string;
    BCRYPT_ROUNDS?: string;
    ADMIN_DEV_BYPASS?: string;
    ADMIN_DEV_USER_ID?: string;
    OPENAI_API_KEY?: string;
}>;
export declare const env: {
    NODE_ENV?: "development" | "production" | "test";
    PORT?: number;
    CORS_ORIGIN?: string;
    JWT_SECRET?: string;
    JWT_EXPIRES_IN?: string;
    DATABASE_URL?: string;
    REDIS_URL?: string;
    SUPABASE_URL?: string;
    SUPABASE_ANON_KEY?: string;
    SUPABASE_SERVICE_ROLE_KEY?: string;
    SMTP_HOST?: string;
    SMTP_PORT?: number;
    SMTP_USER?: string;
    SMTP_PASS?: string;
    FROM_EMAIL?: string;
    FROM_NAME?: string;
    VAPID_PUBLIC_KEY?: string;
    VAPID_PRIVATE_KEY?: string;
    VAPID_SUBJECT?: string;
    ENABLE_CRON_JOBS?: boolean;
    LOG_LEVEL?: "error" | "warn" | "info" | "debug";
    RATE_LIMIT_WINDOW_MS?: number;
    RATE_LIMIT_MAX_REQUESTS?: number;
    AUTH_RATE_LIMIT_MAX_REQUESTS?: number;
    BCRYPT_ROUNDS?: number;
    ADMIN_DEV_BYPASS?: boolean;
    ADMIN_DEV_USER_ID?: string;
    OPENAI_API_KEY?: string;
};
export type Env = z.infer<typeof envSchema>;
export {};
//# sourceMappingURL=env.d.ts.map